server/config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  get("/home", {to: "home#index"})
  get("/about", {to: "about#index"})

  resources :projects do
    resources :members, only: [:create, :destroy]
    resources :tasks, only:[:create, :update, :destroy]
    resources :discussions, only:[:create, :destroy] do
      resources :comments, only:[:create, :destroy]
    end
    resources :favourites, shallow: :true, only: [:create, :destroy]
  end
  resources :tags, only: [:index, :show]
  resources :favourites, only: [:index]
  resources :users, only:[:new, :create, :edit, :update, :destroy]
  resource :session, only:[:new, :create, :destroy]
  # resources :projects, only: [:new, :create, :show, :index, :edit, :update, :destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :projects, only:[:index, :show, :update, :create, :destroy]
      resource :session, only:[:create,:destroy]
    end
  end
end

server/app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks, dependent: :destroy
    has_many :discussions, dependent: :destroy
    has_many :comments, dependent: :destroy
    belongs_to :user, optional: true

    has_many :favourites, dependent: :destroy
    has_many :favouriters, through: :favourites, source: :user
    
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    has_many :members, dependent: :destroy
    has_many :users, through: :members
    
    validates :title, presence: {message: 'must be provided'},uniqueness: true
    validates :due_date, presence: {message: 'must be provided'}
    validate :due_date_after_todays_date

    def tag_names
        self.tags.map(&:name).join(', ')
    end
    def tag_names=(rhs)
        self.tags=rhs.strip.split(/\s*,\s*/).map do|tag_name|
            Tag.find_or_initialize_by(name: tag_name)
        end
    end
    def members_name=(search)
        self.members=search.strip.split(/\s*,\s*/).map do|member|
            # User.where("first_name ILIKE ? OR last_name ILIKE ?", "%#{member}","%#{member}").first
            User.find_or_initialize_by(first_name: member)
        end
    end

    private
    def due_date_after_todays_date
        if due_date < Date.current
            errors.add(:due_date, "can't be before todays date")
        end
    end

end

server/app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_project, only:[:show, :destroy, :update]
    before_action :authorize_user!, only:[:edit, :update, :destroy]

    def index 
        projects= Project.order created_at: :desc
        render json: projects , each_serializer: ProjectCollectionSerializer
    end
    def show
        render json: @project
    end
    def destroy
        if @project.destroy
            head :ok
        else
            head :bad_request
        end
    end
    def create
        project=Project.new project_params
        project.user=current_user
        if project.save
            render json:{id: project.id}
        else
            render(
                json: {errors: project.errors},
                status: 422
            )
        end
    end
    def update
        if @project.update project_params
            render json: {id: @project.id}
        else
            render(
                json: {errors: @project.errors},
                status: 422
            )
        end
    end
    private
    def find_project
        @project=Project.find params[:id]
    end
    def project_params
        params.require(:project).permit(:title, :description, :due_date)
    end
    def authorize_user!
        render(json: {status: 404}, status: 404) unless can?(:crud, @project)
    end
end

server/app/controllers/projects_controller.rb
# [PM Tool] Members
# Add the ability to add one or more members (users in the system) to your projects. List all the members of the project in the display page.

class ProjectsController < ApplicationController
    before_action :find_project, only:[:show, :edit, :update, :destroy]
    def index
        if params[:tag]
            @tag=Tag.find_or_initialize_by(name: params[:tag])
            @projects=@tag.projects.order(created_at: :desc)
        else
            @projects=Project.all.order(created_at: :desc)
        end
        
    end
    def show
        @project_id=params[:id]
        @task=Task.new
        @discussion=Discussion.new
        @comment=Comment.new
        @member=Member.new
        @discussions=@project.discussions.order(created_at: :desc)
        @task_done=@project.tasks.where(done: true)
        @task_undone=@project.tasks.where(done: false)
        @favourite = @project.favourites.find_by_user_id current_user if user_signed_in?
    end
    def destroy
        @project.destroy
        flash[:danger]= 'deleted project'
        redirect_to projects_path
    end
    def new
        @project=Project.new
    end
    def create
        @project=Project.new project_params
        @project.user = current_user
        if @project.save
            redirect_to project_path(@project.id)
        else
            render :new
        end
    end
    def edit
    end
    def update
        if @project.update project_params
            redirect_to project_path(@project.id)
        else
            render :edit
        end
    end
    private
    def find_project
        @project=Project.find params[:id] 
    end
    def project_params
        params.require(:project).permit(:title, :description, :due_date, :tag_names)
    end
end

server/app/helpers/projects_helper.rb
module ProjectsHelper
end

server/app/views/projects/edit.html.erb

<h1>Editing Projects</h1>
<%= render "shared/form" %>

server/app/views/projects/index.html.erb

<% @projects.each do |project|%>
<div class='container card' style="max-width: 700px;">
<h3><%= link_to(project.title, project_path(project.id) )%></h3>
<p> <%= project.description %></p>
<p> <%= project.due_date %></p>
</div>
<% end %>
<br><br>


server/app/views/projects/new.html.erb

<h1>New Projects</h1>
<%= render "shared/form" %>


server/app/views/projects/show.html.erb

<div class="container card" style="max-width: 992px;">
    <h3><%= @project.title%> </h3>
    <p><%= @project.description %></p>
    <p> <%= @project.due_date %></p>
    <div>
        Members: <% @project.members.map do |member| %>
            <span><%= member.user.full_name %></span>
        <% end %>
    </div>
    <% if user_signed_in?  && can?(:crud, @project) %>
        <%= form_with(model: [@project, @member], local: true) do |f| %>
        <div>
        <%= f.text_field :members_name %>
        <%= f.submit class: 'btn btn-outline-success' %>
        </div><br>
        <% end %>
    <% end %>
    <div>Tags: 
        <% @project.tags.each do |tag| %>
            <%= link_to(tag.name, tag_path(tag.id) ) %>
        <% end %>
      </div>
    <small> Created by: <%= @project.user&.full_name || "DELETED" %> </small>
    <small style="font-size:0.55em">
    <p>Last Edited : <%= time_ago_in_words(@project.updated_at)  %> </p>
    <%= link_to "Edit", edit_project_path(@project.id) %> |
    <%= link_to "Delete", project_path, method: :delete,data:{confirm: "Are you sure ?"}, style: "color:red"  %>
    </small>
    <% if user_signed_in?  && can?(:favourite, @project)%>
          <% if @favourite %>
          <%= link_to favourite_path(@favourite), method: :delete do %>
                <i class="fas fa-star"></i>
            <% end %>
            <%#= link_to 'Unfavourite', favourite_path(@favourite), method: :delete %>
          <% else %>
            <%= link_to project_favourites_path(@project), method: :post do %>
                <i class="far fa-star"></i>
            <% end %>
            <%#= link_to 'Favourite', project_favourites_path(@project), method: :post %>
          <% end %>
      <% end %>
    <hr>
    <div class="container-fluid d-flex">
        <div class='col'>
            <strong>-- Done --</strong>
            <% @task_done.each do |done| %>
            <li>
            <span><%= done.title %>
            <small style="font-size:0.55em">
            - due in: <%= time_ago_in_words(done.due_date) %>
            <%= link_to "Delete", project_task_path(@project,done), method: :delete, data:{confirm: "Are you sure ?"}, style: "color:red"  %>   
            </small>
            </li>  
        </span>
            <% end %>
        </div>
        <div class='col'>
            <strong>-- Not Done --</strong>
            <% @task_undone.each do |undone| %>
            <li>
            <span><%= undone.title %>
            <small style="font-size:0.55em">
            - due in: <%= time_ago_in_words(undone.due_date) %>
            <%= link_to "Complete", project_task_path(@project,undone), method: :patch %> 
            | <%= link_to "Delete", project_task_path(@project,undone), method: :delete, data:{confirm: "Are you sure ?"}, style: "color:red"  %>
            </small>
            </span>
            </li>
            <% end %>
        </div>
    </div><br>

    <%= form_with(model: [@project, @task], local: true) do |f| %>
    <div class='d-flex'>
        <%= f.text_field :title, placeholder: :task, class: "form-control col" %>
        <%= f.date_field :due_date, class: "form-control col", style: "max-width: 170px"%>
        <%= f.submit class: 'btn btn-outline-success'%>
    </div><br>
    <% end %>
    <%= form_with(model: [@project, @discussion], local: true) do |f| %>
    <div>
        <%= f.text_field :title, placeholder: :title, class: "form-control" %>
        <%= f.text_area :description, placeholder: :description, class: "form-control" %>
        <%= f.submit class: 'btn btn-outline-success'%>
    </div><br>
    <% end %>
    <% @discussions.each do |discussion| %>
    <hr><span class="d-flex">
    <h5><%= discussion.title %></h5>
    <small style="font-size:0.55em">
        <%= link_to "Delete", project_discussion_path(@project,discussion), method: :delete,data: {confirm: "Are you sure?"}, style: "color:red"  %>
    </small></span>
    <p> <%= discussion.description %></p>
    
    <%= form_with(model: [@project, discussion, @comment], local: true) do |f| %>
    <div class='d-flex'>
    <%= f.text_field :body, placeholder: :comments, class: "form-control col" %>
    <%= f.submit class: 'btn btn-outline-success'%>
    </div><br>
    <% end %>
    <% discussion.comments.each do |c| %>
    <li><span><%= c.body %> 
    <small style="font-size:0.55em">
        comment by <%= c.user&.full_name || "DELETED" %>
        <%= link_to "Delete", project_discussion_comment_path(@project,discussion,c), method: :delete,data: {confirm: "Are you sure?"}, style: "color:red" %>
    </small></span></li><br>
    <% end %>
    <% end %>
    <br>
</div><br><br>
    
<script>
    $(function(){
        $('#member_members_name').selectize({
            delimeter:',',
            persist: false,
            labelField:'email', //Coulmn name in db
            valueField:'email',//Coulmn name in db
            searchField:'email',//Coulmn name in db
            options: <%= User.select(:email).to_json(except:[:id]).html_safe %>,
            create :function(input){
                return{
                    email:input
                }
            }
        })
    })
</script>
  
    
    

    

    