server/config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  get("/home", {to: "home#index"})
  get("/about", {to: "about#index"})

  resources :projects do
    resources :members, only: [:create, :destroy]
    resources :tasks, only:[:create, :update, :destroy]
    resources :discussions, only:[:create, :destroy] do
      resources :comments, only:[:create, :destroy]
    end
    resources :favourites, shallow: :true, only: [:create, :destroy]
  end
  resources :tags, only: [:index, :show]
  resources :favourites, only: [:index]
  resources :users, only:[:new, :create, :edit, :update, :destroy]
  resource :session, only:[:new, :create, :destroy]
  # resources :projects, only: [:new, :create, :show, :index, :edit, :update, :destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :projects, only:[:index, :show, :update, :create, :destroy]
      resource :session, only:[:create,:destroy]
    end
  end
end

server/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
      # user ||= User.new # guest user (not logged in)
      # if user.is_admin?
      #   can :manage, :all
      # end
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action(:create, :read, :update, :delete, to: :crud)
    can(:crud, Project) do |project| 
      user == project.user
    end
    can :favourite, Project do |project|
      project.user != user
    end
    can :destroy, Favourite do |favourite|
      favourite.user == user
    end
  end
end

server/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :discussion
    belongs_to :project
    belongs_to :user, optional: true
    validates :body, presence: {message: 'must be provided'}

end

server/app/models/discussion.rb
class Discussion < ApplicationRecord
    belongs_to :project
    has_many :comments, dependent: :destroy
    belongs_to :user, optional: true
    validates :title, presence: {message: 'must be provided'}

end

server/app/models/favourite.rb
class Favourite < ApplicationRecord
    belongs_to :user
    belongs_to :project

    validates :user_id, uniqueness: {scope: :project_id}
end

server/app/models/member.rb
class Member < ApplicationRecord
  belongs_to :project
  belongs_to :user

  # validates :email, presence: true, uniqueness:{ case_sensitive: false}

  def members_name=(search)
    self.members=search.strip.split(/\s*,\s*/).map do|member|
        User.where("first_name ILIKE ?", "#{member}").first
        # User.find_or_initialize_by(first_name: member)
    end
  end
end

server/app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks, dependent: :destroy
    has_many :discussions, dependent: :destroy
    has_many :comments, dependent: :destroy
    belongs_to :user, optional: true

    has_many :favourites, dependent: :destroy
    has_many :favouriters, through: :favourites, source: :user
    
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    has_many :members, dependent: :destroy
    has_many :users, through: :members
    
    validates :title, presence: {message: 'must be provided'},uniqueness: true
    validates :due_date, presence: {message: 'must be provided'}
    validate :due_date_after_todays_date

    def tag_names
        self.tags.map(&:name).join(', ')
    end
    def tag_names=(rhs)
        self.tags=rhs.strip.split(/\s*,\s*/).map do|tag_name|
            Tag.find_or_initialize_by(name: tag_name)
        end
    end
    def members_name=(search)
        self.members=search.strip.split(/\s*,\s*/).map do|member|
            # User.where("first_name ILIKE ? OR last_name ILIKE ?", "%#{member}","%#{member}").first
            User.find_or_initialize_by(first_name: member)
        end
    end

    private
    def due_date_after_todays_date
        if due_date < Date.current
            errors.add(:due_date, "can't be before todays date")
        end
    end

end

server/app/models/tag.rb
class Tag < ApplicationRecord
    before_save :downcase_name
    has_many :taggings, dependent: :destroy
    has_many :projects, through: :taggings
    validates :name, presence: true, uniqueness:{ case_sensitive: false}
    
    private
    def downcase_name
        self.name&.downcase!
    end
end

server/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :project
  belongs_to :tag
end

server/app/models/task.rb
class Task < ApplicationRecord
    belongs_to :project
    belongs_to :user, optional: true
    validates :title, presence: {message: 'must be provided'} , uniqueness: true

end

server/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :projects, dependent: :nullify
    has_many :tasks, dependent: :nullify
    has_many :discussions, dependent: :nullify
    has_many :comments, dependent: :nullify
    has_many :favourites, dependent: :destroy
    has_many :favoured_project, through: :favourites, source: :project

    has_many :members, dependent: :destroy
    has_many :projects, through: :members

    attr_accessor :current_password, :new_password, :new_password_confirmation
    def full_name
        "#{first_name} #{last_name}"
    end
    def self.search_by_name(search)
        @names = search.split(/\s*,\s*/)
        where("first_name ILIKE ? OR last_name ILIKE ?", "%#{@names}","%#{@names}" )
    end
    
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true, format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :password, presence: true
end

server/app/helpers/about_helper.rb
module AboutHelper
end

server/app/helpers/comment_helper.rb
module CommentHelper
end

server/app/helpers/comments_helper.rb
module CommentsHelper
end

server/app/helpers/home_helper.rb
module HomeHelper
end

server/app/helpers/members_helper.rb
module MembersHelper
end

server/app/helpers/projects_helper.rb
module ProjectsHelper
end

server/app/helpers/tags_helper.rb
module TagsHelper
end

server/app/helpers/task_helper.rb
module TaskHelper
end

server/app/helpers/tasks_helper.rb
module TasksHelper
end

server/app/helpers/users_helper.rb
module UsersHelper
end

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pmtool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%#= flash[:notice] || flash[:alert] %>
    <%= render 'shared/alerts'%>
    <div class="container" style="max-width: 992px;">
      <br>
    <%= yield %>
    </div>
  </body>
</html>

server/app/views/shared/_alerts.html.erb
<%#= flash[:notice] || flash[:alert] %>

<% if flash[:notice].present? %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times; </span>
    </button>
</div>
<% elsif flash[:alert].present? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert]  %> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        &times;
    </button>

</div>
<% end %>

server/app/views/shared/_form.html.erb

<div class="container" style="max-width: 700px;">
    <%= form_with model:@project, :class=>"form-group", local: true do |form| %>
    <% if @project.errors.present? %>
    <%= @project.errors.full_messages.join(', ')%>
    <% end %>
        <%= label_tag :title %>
        <div class="input-group">
            <%= form.text_field :title, :class=>'form-control', :required=>true %>
         </div>
        <%= label_tag :description %>
        <div class="input-group">
            <%= form.text_area :description, cols:50 , rows:5,  :class=>'form-control', :required=>true %>
         </div>
        <%= label_tag :due_date %>
        <div class="input-group">
            <%= form.text_field :due_date, :class=>'form-control' %>
         </div>
         <%= form.label :tag_names  %>
        <%= form.text_field :tag_names %> 
         <br>
         <%=form.submit class: 'btn btn-outline-primary' %> 
        <% end %>
        <br><br>
</div>
<script>
    $(function(){
        $('#project_tag_names').selectize({
            delimeter:',',
            persist: false,
            labelField:'name', //Coulmn name in db
            valueField:'name',//Coulmn name in db
            searchField:'name',//Coulmn name in db
            options: <%= Tag.select(:name).to_json(except:[:id]).html_safe %>,
            create :function(input){
                return{
                    name:input
                }
            }
        })
    })
</script>

server/app/views/shared/_navbar.html.erb

<nav class="navbar navbar-expand navbar-dark bg-dark justify-content-between py-0">
    <%= link_to "Home", home_path, :class=>"navbar-brand mr-auto" %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Project", projects_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
          <%= link_to "New Project", new_project_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
          <%= link_to "Tagged", tags_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
            <%= link_to "About", about_path, :class=>"nav-link" %></li>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Favourites', favourites_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
        <%= link_to current_user.full_name.split.map(&:capitalize).join(' '), edit_user_path(current_user), :class=>"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Logout", session_path, method: :delete,
        data: {confirm: 'Are you sure you want to log out?'}, :class=>"nav-link"
         %>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "Sign In", new_session_path, :class=>"nav-link" %></li>
        </li>
        <li class="nav-item">
            <%= link_to "Sign Up", new_user_path, :class=>"nav-link" %></li>
        </li>
        <% end %>
      </ul>
  </nav>